$schema: "http://json-schema.org/draft-07/schema#"
type: object

properties:
  samples:
    type: string
    description: "Ruta al fichero de muestras"
  
  primary_id_column:
    type: string
    enum: ["id", "id2"]
    description: "Identificador que se empleará para las muestras y los resultados"

  mode:
    type: string
    enum: ["gva", "normal"]
    description: "Modo de análisis"
    
  mode_config:
    type: object
    properties:
      gva:
        type: object
        properties:
          # "Directorio en el que está montado la Cabina de la Conselleria GVA para el copiado de los ficheros"
          storage_cabinet:
            type: string
          hospital:
            type: string
            enum: ["CAST", "ALIC", "LAFE", "PESE", "ELCH", "GRAL", "CLIN", "EPIM"]
        required:
          - storage_cabinet
          - hospital

  outdir:
    type: string
    description: "Directorio de resultados"

  logdir:
    type: string
    description: "Directorio de logs"

  refdir:
    type: string
    description: "Directorio descarga de bases de datos, genomas y demás ficheros necesarios para el análisis fuera de los programas"

  params:
    type: object
    properties:
      min_reads:
        type: integer
      fastp:
        type: object
        properties:
          extra: {type: string}
        required: [extra]
      unicycler:
        type: object
        properties:
          extra: {type: string}
        required: [extra]
      resfinder:
        type: object
        properties:
          extra: {type: string}
        required: [extra]
      kraken2:
        type: object
        properties:
          kraken2_db_url: {type: uri}
        required: [kraken2_db_url]
    required: [min_reads, fastp, unicycler, resfinder, kraken2]

  resources:
    type: object
    patternProperties:
      "^[a-zA-Z0-9_]+$":
        type: object
        properties:
          threads: {type: integer}
          mem: {type: integer}
          walltime: {type: integer}
        required: [threads, mem, walltime]
    additionalProperties: false

  species:
    type: object
    patternProperties:
      "^[a-z_]+$":
        type: object
        properties:
          genome_size:
            type: integer
          refseq:
            type: string
        required: [genome_size, refseq]
    additionalProperties: true

  skip:
    type: object
    description: "Opciones para omitir partes específicas del pipeline"
    properties:
      prokka:
        type: boolean
        description: "Si es true, omite la instalación de bases de datos y ejecución de Prokka"
      # Puedes añadir más opciones en el futuro
    additionalProperties: false
    default: {}

required:
  - samples
  - primary_id_column
  - mode
  - outdir
  - logdir
  - params
  - resources
  - species